apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node-app
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: node-app
          image: $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/node-app:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "300m"
              memory: "512Mi"
            requests:
              cpu: "150m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10